### ISSUE TITLE
The Step struct is missing the label field.

### ISSUE THREAD

**Issue by pmcanseco** [buildkite/go-buildkite#101]
https://github.com/buildkite/go-buildkite/blob/master/buildkite/pipelines.go#L79

It's not clear if `name` is supposed to be used in place of `label`, but if a Step struct is instantiated and then marshaled to YAML in order to pipe it to `buildkite agent pipeline upload` there is no way to specify the `label` field with this schema.

**Comment by jradtilbrook** [comment]
Resolved by #117
