### ISSUE TITLE
Release the next version 🙏🏼

### ISSUE THREAD

**Issue by unrealcloud** [buildkite/go-buildkite#103]
Hello!

There's been many PRs merged since [v3.0.1](https://github.com/buildkite/go-buildkite/releases/tag/v3.0.1) (e.g. [Webhook support](https://github.com/buildkite/go-buildkite/pull/97)). Would be nice to release a new version including all those changes 🙏🏼

**Comment by lizrabuya** [comment]
Released in [v3.1.0](https://github.com/buildkite/go-buildkite/releases/tag/v3.1.0)
