### ISSUE TITLE
CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [buildkite/go-buildkite#109]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in a Buildkite plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it (Similar to terraform provider but much simpler as it is just the Extract part).

This will give your users the ability to sync Buildkite APIs (jobs, config,...) to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by pzeballos** [comment]
Hi @yevgenypats! thanks for reaching us! This sounds very interesting! I'll share this with our Partner Manager so she can reach out to you and start the conversations :)

**Comment by yevgenypats** [comment]
@pzeballos Sounds great! Looking forward to it.

**Comment by james2791** [comment]
Hey @yevgenypats! Hope you have been well 👋

Wanted to reach out to mention that at this point in time (for now), managing a CloudQuery source plugin isn't in the team's agenda, though that being said a Source plugin could always be created externally if there is a demand for it! 

We're also happy to take on PRs for this library too if you believe if things are missing, needs API alignment or if anything is needed specifically.

Thanks again!

James
