### ISSUE TITLE
Consistently use the same Go version in CI and go.mod

### ISSUE THREAD

**Issue by mdb** [buildkite/go-buildkite#113]
If I understand correctly, it seems the [docker-compose.yml](https://github.com/buildkite/go-buildkite/blob/master/docker-compose.yml#L5) used by `go-buildkite` configures the use of Go 1.13 in CI, despite that the [go.mod](https://github.com/buildkite/go-buildkite/blob/master/go.mod#L3) cites Go 1.16. I would think it's preferable to consistently use the Go version cited in `go.mod` in CI too.

**Comment by lizrabuya** [comment]
Resolved in PR #125
