### ISSUE TITLE
build fails with "more than one error-wrapping directive %w" error

### ISSUE THREAD

**Issue by mdb** [buildkite/go-buildkite#114]
In local development using Go 1.19, it appears to me that `make` fails with...

```
$ make
go test -timeout=3s -v ./...
# github.com/buildkite/go-buildkite/v3/buildkite
buildkite/pipelines.go:102:10: fmt.Errorf call has more than one error-wrapping directive %w
FAIL    github.com/buildkite/go-buildkite/v3/buildkite [build failed]
?       github.com/buildkite/go-buildkite/v3/examples/artifacts [no test files]
?       github.com/buildkite/go-buildkite/v3/examples/projects  [no test files]
FAIL
make: *** [test] Error 2
```

If I understand correctly, this is because:

> It is invalid to include more than one %w verb

...as explained at https://pkg.go.dev/fmt#Errorf

I confess I'm not entirely sure why this evidently does not occur during CI, given that I don't believe Go 1.13's `fmt.Errorf` (used in CI) supports more than one `%w`, either. In any case, I'd think the error is probably worth addressing.

**Comment by 53jk1** [comment]
@mdb, can it be closed?

**Comment by mdb** [comment]
Yep - this can now be closed. Thank you!
