### ISSUE TITLE
Job struct is missing `parallel_group_index` and `parallel_group_total`

### ISSUE THREAD

**Issue by yqiu24** [buildkite/go-buildkite#118]
These fields are missing in the Job struct, even though they exist in the Jobs API docs: https://buildkite.com/docs/apis/rest-api/jobs

**Comment by yqiu24** [comment]
Created a PR for this, could someone take a look? https://github.com/buildkite/go-buildkite/pull/119

**Comment by lizrabuya** [comment]
@yqiu24 , this will be part of a patch release 3.2.1. Thanks
