### ISSUE TITLE
HTTP middleware for receiving webhooks.

### ISSUE THREAD

**Issue by chakrit** [buildkite/go-buildkite#12]
It'd be nice if you guys could implement an `net/http.Handler` that automatically parses incoming webhooks into useful structs.

Something like what I've implemented here: https://godoc.org/github.com/omise/omise-go#WebhookHTTPHandler

**Comment by JensRantil** [comment]
[go-github](https://github.com/google/go-github), which this library was inspired by, actually [also bundles structs](https://godoc.org/github.com/google/go-github/github#PullRequestEvent) for their webhook events.

**Comment by sj26** [comment]
Sounds like a nice idea! We'd probably accept a pull request for this, maybe in a separate package within the module.

**Comment by fatmcgav** [comment]
#97
