### ISSUE TITLE
Add support for trigger mode for GithubEnpterpriseSettings

### ISSUE THREAD

**Issue by leakingtapan** [buildkite/go-buildkite#128]
We want to use go-buildkite to programmatically get/set a Github Enterprise pipeline's setting called "trigger_mode" and set it to "none", which is equivalent to the "Disable Github Activity" option from BK UI.

But it appears go-buildkite SDK does not have this option for [GithubEnpterpriseSettings](https://github.com/buildkite/go-buildkite/blob/e988ed44b2302f6c93692c13f6861304f9ecbfd4/buildkite/providers.go#L96) but it exists for [GithubSettings](https://github.com/buildkite/go-buildkite/blob/e988ed44b2302f6c93692c13f6861304f9ecbfd4/buildkite/providers.go#L73). And so we have to use a workaround in our code to update the pipeline setting with the API call.

**Comment by james2791** [comment]
Hello @leakingtapan!

Thanks for raising this with us: I would recommend adding a PR with the `trigger_mode` tested against a GHE installation (since I would assume you are using) and we will assess it once thats in place.

Cheers
