### ISSUE TITLE
Support modifying trigger mode in github settings

### ISSUE THREAD

**Issue by allenhyp** [buildkite/go-buildkite#135]
https://github.com/buildkite/go-buildkite/blob/fa943346d264c3a4fcd3da6f303a71de5c622c71/buildkite/providers.go#L72-L110 
Currently there's no direct support on changing the trigger mode in both github and github enterprise settings, instead it can only be set in the UI.
<img width="864" alt="image" src="https://github.com/buildkite/go-buildkite/assets/6286899/6ef51801-0587-4d9e-bd19-aec641e541b5">
It'd be great to make this workflow in automation within the package.

**Comment by james2791** [comment]
Hey @allenhyp 👋

Thanks for the suggestion! I've got a [PR](https://github.com/buildkite/go-buildkite/pull/149) currently up for review that adds `trigger_mode` to GHE provider settings which will address what you've mentioned above - aligning it to the existing non-enterprise `GitHubSettings` provider settings

**Comment by james2791** [comment]
And its been merged - will be part of the next release 👍
