### ISSUE TITLE
`UnblockJob` gets a 500 server error if you pass `nil` `JobUnblockOptions`

### ISSUE THREAD

**Issue by jfirebaugh** [buildkite/go-buildkite#136]
If you pass `nil` as the last parameter to the `UnblockJob` function, the request receives a 500 Internal Server Error from Buildkite.

If you pass `&buildkite.JobUnblockOptions{ Fields: map[string]string{} }`, then go-buildkite generates the request query string `Fields=map%5B%5D`, which is invalid, but ignored by the API.

The expected behavior is that both `nil` and `&buildkite.JobUnblockOptions{ Fields: map[string]string{} }` work and generate a valid request URL.

**Comment by jradtilbrook** [comment]
Thanks for raising this @jfirebaugh 👍 
We'll be looking at it in the next few weeks. Until then, we accept PR contributions if you are up for it

**Comment by lizrabuya** [comment]
Hi @jfirebaugh , we just released [v3.3.1](https://github.com/buildkite/go-buildkite/releases/tag/v3.3.1) that includes this fix.
