### ISSUE TITLE
Support wrapping an existing http client / transport

### ISSUE THREAD

**Issue by vikstrous** [buildkite/go-buildkite#14]
Looks like the TokenConfig and NewBasicConfig have the DefaultTransport hardcoded. It would be nice if they accepted a user provided transport and optionally used that in case the user wants to configure TLS, timeouts, etc.

**Comment by sj26** [comment]
Sounds like a nice idea! We'd accept a pull request doing this. :-)

**Comment by jradtilbrook** [comment]
We are closing this due to low activity
