### ISSUE TITLE
Support uploading to Test analytics

### ISSUE THREAD

**Issue by jeremybumsted** [buildkite/go-buildkite#140]
Since uploading test results to Test Analytics is as simple as a curl, it would be slick if we could include it in go-buildkite :)
https://buildkite.com/docs/test-analytics/golang-collectors#main

**Comment by james2791** [comment]
@jeremybumsted 💪
https://github.com/buildkite/go-buildkite/pull/142

**Comment by james2791** [comment]
Included as part of [3.4.0 ](https://github.com/buildkite/go-buildkite/releases/tag/v3.4.0)- will wrap this up 👍
