### ISSUE TITLE
Using buildkiteClient.Pipelines.AddWebhook returns a 404 instead of the expected 201

### ISSUE THREAD

**Issue by gilwesdigital** [buildkite/go-buildkite#166]
**Describe the bug**

Hi team. I am seeing an issue with this method in the Golang SDK for Buildkite pipelines:
```
_, errBuildkite := buildkiteClient.Pipelines.AddWebhook(owner, repositoryName)
```

https://github.com/buildkite/go-buildkite/blob/ce5f39ad54ed81bced7e808507bd9a6ad95f5e3a/buildkite/pipelines.go#L265

When I try to add a webhook to an existing pipeline, instead of receiving a 201 as expected (https://buildkite.com/docs/apis/rest-api/pipelines#add-a-webhook), I get a 404:
```
POST https://api.buildkite.com/v2/organizations/Wesfarmers-Digital/pipelines/myrepo/webhook: 404 Not Found
```

I confirmed that the repository exists in Github, that the pipeline exists in Buildkite too. 
Out of 6+ tries, only 2 succeeded

**To Reproduce**
1. Create a github repository using this github golang cdk function: `client.Repositories.CreateFromTemplate` (github.com/google/go-github/v54/github)
2. Create a buildkite pipeline for this repository using this buildkite golang cdk function: `buildkiteClient.Pipelines.Create`
3. Create a webhook on the github repository through this buildkite golang cdk function: `buildkiteClient.Pipelines.AddWebhook`

**Expected behavior**
I would expect to receive a 201 HTTP return code.

**Additional context**
I repeated the webhook creation step a few times after creating the repository and the pipeline.

**Comment by james2791** [comment]
Thanks for raising this @gilwesdigital !

We'll aim to try reproduce this and see what the resolution/fix will involve

**Comment by james2791** [comment]
Hey @gilwesdigital 👋

Did some assessment and pretty much can add webhooks as expected - some follow up questions on my side in triaging this:

- What version of Go-Buildkite as you using currently? (I'm using both `v3.8.0` and as a maintainer, the codebase from `main` as the basis
- Do webhook exist for your specific pipelines already? You'll get a `422` if one exists for a pipeline already, but a `404` indicates that this indicates that either the entered in organisation/pipeline combination to `AddWebhook` is producing a URL whom the API cannot find said pipeline to add a webhook for.

**Comment by gilwesdigital** [comment]
I am still using go-buildkite v3.6.0, but I can try to upgrade to see if it makes a difference.
In this example the webhook does not exist. 
- I create a new github repository using go-github v54.0.0
- Then I create a buildkite pipeline using go-buildkite
- Then I add a webhook to the github repository using the go-builkite library
Should I wait between the creation of the repository and the creation of the pipeline?

**Comment by james2791** [comment]
The version jump shouldn't make too much difference here, as the adjustments were mainly around adding interaction to additional API endpoint interaction!

You shouldn't have to wait for repo/pipeline creation - you could technically add the webhook as soon as they're made. I'm _pretty sure_ its a byproduct of permissions on tokens & user permissions on Teams, but shall continue to assess!

**Comment by james2791** [comment]
Hey @gilwesdigital!

Thanks for your patience which this is looked at on our side. I've gone and attempted to get a `404` on my end from the repro process you've detailed quite a few times and all successful (create the repo from a template via Go-GitHub, create a pipeline in BK and then add a webhook from our library).

Just wondering if you've encountered this in the time since above? (I was on break so didn't get a good chance to dig into this!)

**Comment by james2791** [comment]
Hey @gilwesdigital!

I think this might be drawn to a timing case - most times I've did the repro (create repo from template on GitHub from then making the pipeline and webhook respectfully) is circa 5ish seconds - and each times results in a `201` from my assessments - leading me to this potentially being a race condition in timing between the repo being made from Go-GitHub to then Go-BK creating the pipeline and webhook.

I'll whip this closed for now as I believe this is a result of the above, but if you do happen to find/see this again, please let me know! 🙂
