### ISSUE TITLE
Author struct missing username

### ISSUE THREAD

**Issue by mattdee123** [buildkite/go-buildkite#172]
**Describe the bug**
The build [Author](https://github.com/buildkite/go-buildkite/blob/fed56ba/buildkite/builds.go#L18) struct only contains a name and email. However, in a `build.finished` webhook, I see it also having a `username` field. It would be nice to have that in the struct as well to help when unmarshalling webhook events.

```
"author": {
  "name": "Matthew Dee",
  "username": "mdee",
  "email": "[redacted]"
},
```

**Comment by james2791** [comment]
Hey @mattdee123 👋

Thanks for raising this with us - and I believe what we should be potentially altering is the build finished webhook event (specifically the [typed](https://github.com/buildkite/go-buildkite/blob/main/buildkite/webhook_events.go#L50-L55) `buildEvent`). The `Author` of the `CreateBuild` type you [linked](https://github.com/buildkite/go-buildkite/blob/fed56ba/buildkite/builds.go#L18) to is specifically used for REST API build#create POST requests - and specific webhook event type refers to [this](https://github.com/buildkite/go-buildkite/blob/fed56ba753dab99fa9842184394d255b8f6ca016/buildkite/user.go#L14-L19) `User` type.

I think we could potentially wrap this up under the struct literal [ticket](https://github.com/buildkite/go-buildkite/issues/170) that was previously asked on (convert and also introduce specific types)
