### ISSUE TITLE
Pipeline struct is unable to Unmarshall wait steps correctly

### ISSUE THREAD

**Issue by migueleliasweb** [buildkite/go-buildkite#180]
**Describe the bug**

[Buildkite has a heretogenous definitions](https://buildkite.com/docs/pipelines/step-reference) of `steps`. This means, steps `can` have very different formats. Take the `wait` steps for example, it has none of the keys the `command` steps have.

This breaks the way Go wants to work with `pipeline` steps as they are currently tied to a single type called `Step`. Ideally this should come from an interface (something like `PipelineStep`) that allows different types of step to implement their own decoding strategy.

**To Reproduce**

Given the below pipeline:

```yaml
# pipeline.yaml
---

steps:
  - name: "Command 1"
    command: ls

  - wait: ~

  - name: "Command 2"
    command: ls
```

The below code fails to correctly Unmarshall the YAML to the Go structure:

```go
pipeline := &buildkite.Pipeline{}

pipelineYAMLBytes, err := os.ReadFile("./pipeline.yaml")

if err != nil {
	panic(err)
}

err = yaml.Unmarshal(pipelineYAMLBytes, pipeline)

if err != nil {
	panic(err)
}

waitStepBytes, err := yaml.Marshal(pipeline.Steps[1])

if err != nil {
	panic(err)
}

fmt.Println(string(waitStepBytes))
```

The output of the `wait` step is an empty `step`, which makes it impossible to work with this data as you wouldn't be able to tell what the step is supposed to do. Note that any other `step` type other than the `command` step will have the same behaviour.

**Expected behavior**

**Additional context**

This hinders the ability for the SDK to be used in various common usecases of BK.

If the BK team is interested, I'm happy to work alongside you to create a workable solution.

Thanks.

**Comment by mcncl** [comment]
Hey @migueleliasweb! Thanks for the detailed issue! We'll take a look in to this and see what we can work on, it seems like a valid issue and one we should consider improving the functionality around.

The `interface` use is a good call out, we'll look in to that as a solution. I'll use this issue as a base for communications on this issue and our progress/plans on tackling it 🙂

**Comment by migueleliasweb** [comment]
Thanks for jumping in, @mcncl.

In the interim, I'll be forced to create my own implementation to get my code working. I'm happy to share what I come up with if you're interested.

On a different note, I also noticed there is an (somewhat) unsupported feature for pipelines that are solely loaded directly from code (in my case I had many many pipelines where the only "step" set in the UI is `- command: buildkite-agent pipeline upload` and that loads the actual pipeline steps from a file existing on the repo itself).

Such pipelines, when fetched from the API come back with only that single step that was defined in the UI itself (I can kinda understand the reason behind this, as full pipeline is a `runtime` construct and not necessarily defined statically). But this introduces a new challenge where a "full" pipeline view like the UI provides is non-existent using the SDKs.

I wonder if there is a way to add a method in the `PipelineService` so it can load `yaml` files containing pipelines. This will be super useful for mimicing that behaviour.

**Comment by migueleliasweb** [comment]
I just came across something odd. Apparently Buildkite already has a solution for this but it happens not to be available for this repo. 

I knew that calling `buildkite-agent pipeline upload` worked basically for any kind of pipeline. Turns out there is another repo called https://github.com/buildkite/go-pipeline and this repo has a properly `interfaced` Pipeline definition. It's used by the agent itself to parse and send the pipeline to the SaaS backend.

As you can see in https://github.com/buildkite/agent/blob/main/clicommand/pipeline_upload.go#L392 it calls another pipeline type defined in https://github.com/buildkite/go-pipeline/blob/main/parser.go#L24.

**Comment by migueleliasweb** [comment]
Any news about this issue?

**Comment by mcncl** [comment]
Hey @migueleliasweb! Apologies for the radio silence.

I've scheduled this piece of work in for the next cycle, which is in 2 days time.

**Comment by migueleliasweb** [comment]
Some insights from the past 2 weeks:

- The `go-buildkite` package does not provide similar functionalities as a fully fledged Buildkite agent, such as adding pipeline steps like in `myscript.s | buildkite-agent pipeline upload`
- The pipeline definition from `go-pipeline` is way more complex and fully featured compared to `go-buildkite`'s pipeline definitions as it supports heterogenous step definitions via an `interface` and provides other helper functions to marshall its contents
- The `agent` API is annoyingly not very `public`, meaining it's not documented publicly so if you want to perform any complex actions you'll have to juggle between undocumented api endpoints from the agent (by importing the Go modules) + using the `go-buildkite` SDK for some of the rest endpoints + using a graphQL client for interacting with the remaining endpoints.

**Comment by lizrabuya** [comment]
hi @migueleliasweb , thanks for the detailed insights on our SDK. We are now looking at how to improve the library to be able to handle all the heterogenous step definitions when marshalling the contents. 

The `go-buildkite` library only supports what is available in our [API](https://buildkite.com/docs/apis/rest-api) . There are known differences with the REST API and GraphQL API and the current limitations both API's have. Therefore we understand that there is a need to use both when an endpoint is not supported by the other.  And we are aware that a lot of improvements can still be added into the API.

**Comment by migueleliasweb** [comment]
Thanks for the follow up @lizrabuya .

The third item regarding the `agent` API is also quite important in some usecases as if you want to create a "smart" step ( let's say a container running custom code) that wants to manipulate the current pipeline, currently the only reliable way to do so is to call a subcommand of `buildkite pipeline upload`.

I tried my best to import packages such as [PipelineUploader](https://github.com/buildkite/agent/blob/5af3edd6b634afaac7263fe318b6b0715cc6ca1c/agent/pipeline_uploader.go#L27) directly of `https://github.com/buildkite/agent` without any success due to the hidden requirements such as env vars, access to the agent config, agent token, etc. Having those features more readily accessible and documented will help much deeper integrations to Buildkite services.

**Comment by lizrabuya** [comment]
Hi @migueleliasweb , the subcommand `buildkite pipeline upload` currently does not have an equivalent function with our API, thus it is not available in the `go-buildlkite` SDK. Only until that function is supported from our API, will it be implemented in our SDK.  This library is intended for using our API's programatically using go, and not as an alternate to the agent itself.  

On the issue on unmarshalling the pipeline using `buildkite.pipeline{}` object, we will do improvements on this. However, this should not be blocking you.  To parse the contents from the pipeline YAML as returned from the  [get pipeline API](https://buildkite.com/docs/rest-api/pipelines#get-a-pipeline) , you can make use of the [go-pipeline](https://github.com/buildkite/go-pipeline) library to do that. 

```
       p, err := pipeline.Parse(strings.NewReader(string(pipelineYAMLBytes)))
	if err != nil {
		panic(err)
	}

	if index >= len(p.Steps) {
		return
	}

	stepBytes, err := yaml.Marshal(p.Steps[index])

	if err != nil {
		panic(err)
	}

	fmt.Println(string(stepBytes))
 ```

**Comment by migueleliasweb** [comment]
Hi @lizrabuya , that's precisely what I ended up doing.

I've used the `go-pipeline` after digging a bit on how the agent did it 😁.

Looking forward to have this natively supported in the sdk!

**Comment by migueleliasweb** [comment]
(sorry I now this issue is already closed but....)

Is there any plans on supporting (specially) the 'upload pipeline' calls to be done programatically?

Currently, the only _documented_ way is to call the `buildkite-agent pipeline upload` as a subcommand (if one is building something within a programming language). It would be great is those agent APIs could at least be documented so ease how to fully integrate it and avoid the subprocess call.

**Comment by jradtilbrook** [comment]
hey @migueleliasweb thanks for understanding. We would like to make some major changes to this SDK but they are breaking so need to wait for a v4. And we would like to start looking into that next year and we will consider incorporating go-pipeline directly or at least a similar API here so its much more usable.

But as for documenting and opening up the agent API, its unlikely. We have so far kept that undocumented on purpose so that we don't have exactly what you are wanting to do: external things hitting that API adding dependencies outside of our control. So that we can allow changing it more freely without breaking others usage. 

With that in mind, your best bet would be to make use of the upload command in the agent within your program
