### ISSUE TITLE
Pipeline struct is missing created_by

### ISSUE THREAD

**Issue by nitzan-entro** [buildkite/go-buildkite#182]
Pipeline struct is missing created_by

**Comment by jradtilbrook** [comment]
Hi @nitzan-entro I can see the created at field here: https://github.com/buildkite/go-buildkite/blob/95b66e0d3c4cf264db91902ca1ea92ddd713b370/buildkite/pipelines.go#L73

Are you talking about somewhere else?

**Comment by nitzan-entro** [comment]
![Screenshot 2024-05-13 at 13 18 49](https://github.com/buildkite/go-buildkite/assets/147926763/0205eb54-18f5-4725-991b-60f812a8203d)

@jradtilbrook in the API there's created_by field which doesnt exist on the sdk

**Comment by jradtilbrook** [comment]
Ohh right I see 👍 
Do you want to submit a PR to add that field to the Pipeline struct?
