### ISSUE TITLE
Most fields in /v2/org/agents are nil

### ISSUE THREAD

**Issue by smarthall** [buildkite/go-buildkite#28]
So suddenly this morning the go-buildkite library randomly stopped working. The issue appears as most fields in the agent list appearing as `nil`.

`curl -s -H 'Authorization: Bearer <token>' "https://api.buildkite.com/v2/organizations/org/agents"` - worked
`curl -s -H 'Authorization: Bearer <token>' --user-agent 'go-buildkite/2.0.0' "https://api.buildkite.com/v2/organizations/org/agents"` - was missing information

It looks like the server is sending a different response when the user agent is `go-buildkite/2.0.0`, not sure why that would be, but I assume you have your reasons.

That said I thought I was using v2.1.0 of the library!

Then I found this: https://github.com/buildkite/go-buildkite/blob/v2.1.0/buildkite/version.go

It looks like the version number wasn't updated in the latest release.

So, can we please get a new release of go-buildkite with a working user agent? The one in master seems fine ...

**Comment by JensRantil** [comment]
I experienced this last week, too. It took me at least an hour to figure out that the API was `User-Agent` dependent.

Firstly, I think that's very bad-practise from an API standpoint. That said, I propose that at least https://github.com/buildkite/go-buildkite/blob/9d3e34793648cb91382765ef6f4ac4579616ee1c/buildkite/buildkite.go#L29 doesn't default to something yielding a limited subset of fields.

Workaround is to change https://github.com/buildkite/go-buildkite/blob/9d3e34793648cb91382765ef6f4ac4579616ee1c/buildkite/buildkite.go#L46 (`UserAgent`) to something specific to you.

@smarthall Your description above is actually two issues; One regarding `nil` fields, and another regarding version not set correctly for the library. Could you please create a separate issue (and update description) for the version issue?

**Comment by toolmantim** [comment]
Sorry we never commented here about the change in returned data! Unfortunately the agent metrics tool, which uses this library, was causing a disruptive amount of load. It also didn’t set a custom user agent. 


In order to stop service problems, we had to selectively return JSON fields for the existing agent metrics daemons based on a generic user agent pattern used here. It won’t happen for future versions, and setting a different user agent is the workaround for now.

Sorry for missing this issue, and the problems it might have caused you!

**Comment by lox** [comment]
> Firstly, I think that's very bad-practise from an API standpoint. 

Apologies folks! We totally agree that user-agent specific behaviour is terrible and would avoid it at almost any cost. 😢 We should have done a better job of documenting this nuance in this library.

**Comment by JensRantil** [comment]
Have you set a custom user-agent on all agents now?

**Comment by toolmantim** [comment]
Yep, that was done in https://github.com/buildkite/buildkite-agent-metrics/pull/34

**Comment by nhooyr** [comment]
Could you guys cut a new release for https://github.com/buildkite/go-buildkite/commit/9d8a7ff1f4f0394a50efa26b0697344a603918dd

Would prefer to not have to use master.

**Comment by lox** [comment]
We've cut a new release for v2.2.0. I'm going to close this as it shouldn't happen with more recent user agents!
