### ISSUE TITLE
Avoid stuttering in package path

### ISSUE THREAD

**Issue by JensRantil** [buildkite/go-buildkite#34]
The package path is `github.com/buildkite/go-buildkite/buildkite`. That's `buildkite` three times. I propose at least removing one of them to `github.com/buildkite/go-buildkite`. Creating yet another Go package doesn't seem to be idiomatic Go from what I've seen elsewhere on Github.

**Comment by lox** [comment]
Agreed @JensRantil, as a golang dev it's always bothered me. It would be a major BC break is the thing that has prevented me from cleaning it up. Any suggestions?

**Comment by lox** [comment]
For non-golang folks, this is context: https://blog.golang.org/package-names

**Comment by JensRantil** [comment]
> It would be a major BC break is the thing that has prevented me from cleaning it up. Any suggestions?

If dependees are vendored they should not be impacted. The repo [_is_ versioned](https://github.com/buildkite/go-buildkite/releases), which means that all dependees that are using versioning tools such as `dep`, `go mod` etc. should be either 1) safe or 2) in a spot where they easily could lock to current release.

The big question is if you'd like to be able to be backwards compatible with all dependees that are pointing to your `master` branch. I'd say that's considered really bad practise and, if so, they should start versioning their dependencies.

**Comment by JensRantil** [comment]
👏
