### ISSUE TITLE
pipelines with a slash

### ISSUE THREAD

**Issue by nhooyr** [buildkite/go-buildkite#35]
Does the REST API handle pipelines with a slash in them?

I'm having trouble using the API to get a pipeline on my account with a slash in it. Pipelines without a slash in them work fine.

 E.g. get on pipeline `mtest` works but get on pipeline `lib/somefoo` does not.

I've tried URL escaping the pipeline slug before sending it over and this too does not work.

**Comment by toolmantim** [comment]
The slug for `lib/somefoo` should be `lib-somefoo` — are you not finding that? You can see the slug by browsing the web UI and looking for the URL part that relates to the pipeline name.

**Comment by nhooyr** [comment]
Ah, thank you.
