### ISSUE TITLE
Release 2.2.0 doesn't have a tag released with it

### ISSUE THREAD

**Issue by charlottestjohn** [buildkite/go-buildkite#38]
Hey! Looks like version 2.2.0 was released 5 days ago; but the tag was not updated to reflect this (which most dep managers need to have the version instead of latest)

I think the solution is as simple as tagging master with v2.2.0

**Comment by lox** [comment]
You are completely correct, I neglected to actually release it.

**Comment by lox** [comment]
I've just put out a release!
