### ISSUE TITLE
Time for next release?

### ISSUE THREAD

**Issue by qinjin** [buildkite/go-buildkite#78]
Hello! When will the next release being created? I've recently submitted a [change](https://github.com/buildkite/go-buildkite/pull/77) and would like to get a new release so that we can start to use that field. 

Thanks!

**Comment by ticky** [comment]
Hi @qinjin, I've just published [v2.6.0](https://github.com/buildkite/go-buildkite/releases/tag/v2.6.0)! Sorry for the delay :)

**Comment by qinjin** [comment]
Thank you! No worries @ticky:)
