### ISSUE TITLE
Separate the models and the wire/cli code?

### ISSUE THREAD

**Issue by tobyjoe** [buildkite/go-buildkite#8]
I'm working on some template-tooling that (among other things) automates buildkite set-up when folks want to create a new service or stack. It doesn't do any of the remote execution work - only creating the `.buildkite` directory with a bunch of defaults; creating Cloudformation/Terraform stuff for the CI stacks; and things like that. It's then up to the project team to execute things remotely.

This package*\* is pretty great for dealing with the remote API but it feels a little bit coupled, in a sense. 

Would it be a Bad Idea :tm: to separate the data models from the service implementation and auth?

Like, to build something using the remote API:

```
import (
  "github.com/buildkite/go-buildkite/buildkite"
  "github.com/buildkite/go-buildkite/buildkite/models"
)

```

But, to build something using only the data models (for file generation):

```
import (
  "github.com/buildkite/go-buildkite/buildkite/models"
)

```

That should make the current API stable:

``` go
client := buildkite.NewClient(config.Client())
projects, _, err := client.Projects.List(*org, nil)

```

I know there's always a back and forth on Go projects about flat or nested package spaces... I'm happy to do the refactoring, but don't want to do so if it clashes with the maintainers' preferences, as it's more a preference than anything else.

_(not yet OSS - pending some company conversations)
*_(It's awesome to see the go-buildkite project in the buildkite org, btw!)

**Comment by wolfeidau** [comment]
Yeah at this stage I would prefer to keep it flat.

I normally try and avoid modules with common names, at least until they NEED a package.

Not sure what @lox prefers.

**Comment by lox** [comment]
If anything, I'd suggest renaming this to `go-buildkite-api` so that it's very specific what it does. I'd also be -1 to abstraction of this stuff, the models are simple enough that copy and paste makes sense.
