### ISSUE TITLE
support using go context

### ISSUE THREAD

**Issue by sluongng** [buildkite/go-buildkite#98]
In Golang, propagating context through the stack is very important:

1. Let you retain a certain metadata
2. Let you handle graceful shutdown logic
3. Let you implement cancel/timeout

Current library has not support for making http request with a context.

We could introduce `RequestOptionFunc` to help handle this (see https://github.com/xanzy/go-gitlab/blob/7d79a18484610e0d7b178392f020c4a8dfb419c6/applications.go#L75-L91 for reference)

```
// RequestOptionFunc can be passed to all API requests to customize the API request.
type RequestOptionFunc func(*retryablehttp.Request) error[Sander van Harmelen, 2 years ago: • Introduce client options](https://sourcegraph.com/github.com/xanzy/go-gitlab/-/commit/443faa191281c0e6dd2d6df9c29c2d1caa515d4d)

// WithContext runs the request with the provided context
func WithContext(ctx context.Context) RequestOptionFunc {
	return func(req *retryablehttp.Request) error {
		*req = *req.WithContext(ctx)
		return nil
	}
}
```

The modify existing interfaces to 

```
func (*obj) ListObj(lo ListObjOptions, options ...RequestOptionFunc) ([]*Obj, *Response, error) {}
```

This would help it so that if parent application decided to shutdown half way through, we can cancel the in-flight request early (before the server even response)

**Comment by jradtilbrook** [comment]
Hey @sluongng this sounds like a really good idea. Are you open to creating a PR to add this functionality?

**Comment by sluongng** [comment]
I no longer work with buildkite on a day to day basis so I think it's best to leave it to someone else.
